# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='message.proto',
    package='cdlp',
    syntax='proto3',
    serialized_pb=_b(
        '\n\rmessage.proto\x12\x04\x63\x64lp\"^\n\x0b\x43\x64lpMessage\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04\x63hat\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\r\x12\x12\n\nanchorName\x18\x05 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CDLPMESSAGE = _descriptor.Descriptor(
    name='CdlpMessage',
    full_name='cdlp.CdlpMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='type', full_name='cdlp.CdlpMessage.type', index=0,
            number=1, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='chat', full_name='cdlp.CdlpMessage.chat', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='userName', full_name='cdlp.CdlpMessage.userName', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='level', full_name='cdlp.CdlpMessage.level', index=3,
            number=4, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='anchorName', full_name='cdlp.CdlpMessage.anchorName', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=23,
    serialized_end=117,
)

DESCRIPTOR.message_types_by_name['CdlpMessage'] = _CDLPMESSAGE

CdlpMessage = _reflection.GeneratedProtocolMessageType('CdlpMessage', (_message.Message,), dict(
    DESCRIPTOR=_CDLPMESSAGE,
    __module__='message_pb2'
    # @@protoc_insertion_point(class_scope:cdlp.CdlpMessage)
))
_sym_db.RegisterMessage(CdlpMessage)

# @@protoc_insertion_point(module_scope)
